name: Create a comment on new issues

on: 
  issues:
    types: [opened]

permissions:           
  issues: write          

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        shell: bash

      - name: Dump GitHub Context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Debugging Information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Comment With API
        run: |
          gh api -X POST \
            /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -f body='Comment from API call, not action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
